model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.05
    use_ema: true
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        use_checkpoint: True
        context_dim: 512
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ckpt_path: /workspace/ml-figs-ldm/models/AutoencoderKL(14-02-2024)_epoch_11_dataset_MlFigsSciCap.ckpt
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 512
        n_layer: 12

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 7
    num_workers: 128
    wrap: false
    train:
      target: ldm.data.ml_figs.MlFigsTrain
      params:
        json_file: /workspace/ml-figs-ldm/dataset/ml-scicap-figs/train.json
        size: 512
        text_modality: 1
        random_crop: false
        square_pad: True
        use_roi_bboxes: True
    validation:
      target: ldm.data.ml_figs.MlFigsValidation
      params:
        json_file: /workspace/ml-figs-ldm/dataset/ml-scicap-figs/test.json
        size: 512
        text_modality: 1
        random_crop: false
        square_pad: True
        use_roi_bboxes: True
    test:
      target: ldm.data.ml_figs.MlFigsValidation
      params:
        json_file: /workspace/ml-figs-ldm/dataset/ml-scicap-figs/test.json
        size: 512
        text_modality: 1
        random_crop: false
        square_pad: True
        use_roi_bboxes: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 4
        increase_log_steps: false
  
  trainer:
    accumulate_grad_batches: 4
    benchmark: true
    accelerator: gpu
    max_epochs: 400
    gpus: 0,